### ISSUE TITLE
Does this work on FreeCAD v0.19.x

### ISSUE THREAD

**Issue by luzpaz** [Athanaze/Freecad-easy-reflections#2]

**Comment by Athanaze** [comment]
Yep. I just tested it on this build :
FreeCAD_0.19-20943-Linux-Conda_glibc2.12-x86_64.AppImage

And it works fine.

**Comment by luzpaz** [comment]
Would you be interested in sharing this on the [FreeCAD forums](https://forum.freecadweb.org) ?

**Comment by luzpaz** [comment]
https://forum.freecadweb.org/viewtopic.php?f=22&t=47604
Thanks!
